#!/usr/bin/env bash

set -euo pipefail

#
# Run an XSLT transformation on all files listed on standard in.
#

xsl="$1"

while read -r f; do
    out=$(mktemp)
    if xsltproc "$xsl" "$f" > "$out"; then
        mv "$out" "$f"
        xml-format -i "$f"
    else
        echo "Problem processing $f with $xsl"
    fi
done
