#!/usr/bin/env bash

set -euo pipefail

#
# Run an XSLT transformation in place on all files listed on standard in,
# reformatting each afterwards:
#
#     fd -e ptx . <book>/source | scripts/transform some.xsl
#

xsl="$1"

while read -r f; do
    out=$(mktemp)
    if xsltproc "$xsl" "$f" > "$out"; then
        mv "$out" "$f"
        xml-format -i "$f"
    else
        echo "Problem processing $f with $xsl"
    fi
done
